language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - libgeos-dev

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# command to run the dependencies
script:
  - pipenv run pytest
  - pipenv run autopep8 --in-place ./**/*.py
  - git diff --quiet
